build:
  version: 3.0
loans:
  message: "Welcome to Loans Service API"
  contactDetails:
    name: "Serhii default profile"
    mail: "serhii@example.com"
  onCallSupport:
    - (555) 555-5555
    - (444) 444-4444