spring:
  application:
    name: "configserver"
  profiles:
    active: native
#    active: git
  cloud:
    config:
      server:
#        native:
          search-locations: "classpath:/config/"
#          search-locations: "file:///Users//mac//Learning//udemy-easybytes//config"
#        git:
#          uri: "https://github.com/eazybytes/eazybytes-config.git"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true
encrypt:
  key: "111aaa222bbb333ccc"
server:
  port: 8071
